# Numpy Library

- Numpy stands for Numerical Python

- It aims to provide an array object which is 50x faster than traditional python list.

- The array object in Numpy is called "ndarray"

# But Why Numpy is faster than Lists ?

- Numpy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

- This is behavior is called locality of reference in computer science.

# First Line of Code in Numpy

- Making a simple array 

In [1]:
# Importing Numpy library

import numpy as np

# Fist numpy code: Making an array

arr = np.array([1,2,3,4,5])
arr


array([1, 2, 3, 4, 5])

In [2]:
# Checking the type of array

type(arr)

numpy.ndarray

# Dimensions In Array

 There are 4 dimensions of an array
 - 0-D (Scalars)
 - 1-D (Vectors)
 - 2-D (Tensors)
 - 3-D (Tensors)

# 0-D Array

In [3]:
arr_0_D = np.array(21)
arr_0_D

array(21)

# 1-D Array

In [4]:
arr_1_D = np.array([1,2,3,4,5])
arr_1_D

array([1, 2, 3, 4, 5])

# 2-D Array

In [5]:
arr_2_D = np.array([[1,3,5],[2,4,6]])
arr_2_D

array([[1, 3, 5],
       [2, 4, 6]])

# 3-D Array

In [6]:
arr_3_D = np.array([[[1,3,5],[2,4,6]],[[7,9,11],[8,10,12]]])
arr_3_D

array([[[ 1,  3,  5],
        [ 2,  4,  6]],

       [[ 7,  9, 11],
        [ 8, 10, 12]]])

# Checking Number of Dimensions of above Arrays

In [7]:
arr_0_D.ndim

3

In [8]:
arr_1_D.ndim

1

In [9]:
arr_2_D.ndim

2

In [10]:
arr_3_D.ndim

3

# Checking the Shape of the array

In [7]:
import numpy as np

# Finding the Shape of 0-D array which is a scalar quantity
arr_0_D = np.array(21)
arr_0_D.shape

()

In [8]:
# Finding the Shape of 1-D array
arr_1_D = np.array([1,2,3,4,5])
arr_1_D.shape

(5,)

In the above the arr_1_D.shape command returns the output of (5,) which shows that it has 5 rows and no columns

In [10]:
# Finding the Shape of 2-D array
arr_2_D = np.array([[1,3,5],[2,4,6]])
arr_2_D.shape

(2, 3)

The above array is a matrix of 2 rows & 3 columns

In [11]:
# Finding the Shape of 3-D array
arr_3_D = np.array([[[1,3,5],[2,4,6]],[[7,9,11],[8,10,12]]])
arr_3_D.shape

(2, 2, 3)

This shows that in 3-D array we have 2 2-D arrays which has the shape of 2 rows & 3 columns.

Hence, for further understanging (2,2,3) is just like (How many 2_D arrays are there, rows , columns)

# Other methods of creating arrays

- zeros method
- ones method
- empty method
- linspace method
- arange method

# Arrays from zeros method

In [12]:
# 1-D array of zero
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [13]:
# 2-D array of zero
arr = np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
# 3-D array of zero
arr = np.zeros((2,3,3))
arr

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

# Arrays from ones method

In [16]:
# Creating 3-D array of ones
arr = np.ones((3,2,3))
arr

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

# Array from empty method

In [17]:
# Creating 2-D empty array
arr = np.empty((3,3))
arr

array([[ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  5.47424736e-321],
       [-2.95504102e+003,  4.24399158e-314,  1.90979621e-313]])

In [19]:
arr.dtype

dtype('float64')

This empty method jus gives "garbage" values randomly which are not initialized

# Array from linspace method

This linspace gives an array of required number within a range given by you.

In [20]:
arr = np.linspace(2,20, num=10)
arr

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [21]:
arr = np.linspace(1,10, num=7)
arr

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

The above arrays are 1-D arrays. Now below are the methods to create 2-D & 3-D arrays from linspace method.

In [26]:
# Creating a 2-D array is not so simple 

# For the first column: From 1 of (1,2) to 10 of (10,20), put the increasing 10 numbers.
# For the second column: From 2 of (1,2) to 20 of (10,20), put the incresing 10 numbers.

arr = np.linspace((1,2),(10,20),10)
arr

array([[ 1.,  2.],
       [ 2.,  4.],
       [ 3.,  6.],
       [ 4.,  8.],
       [ 5., 10.],
       [ 6., 12.],
       [ 7., 14.],
       [ 8., 16.],
       [ 9., 18.],
       [10., 20.]])

# Sorry Sir I can't Find a way to create a 3D array using linspace

# Array from arange method

In [35]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [42]:
# To create a 2-D array using arange method we have to use a combine formation of arange & reshape function

# But in this we have to focus on the inputs which we are giving

# In parantheses of arange function we have to give a value which is a product of rows & columns of reshape function.

arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [51]:
arr = np.arange(3,30,step=3).reshape(3,3)
arr

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [53]:
# Creating a 3D array using arange & reshape function

arr = np.arange(27).reshape(3,3,3)


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [57]:
arr = np.arange(3,84,step=3).reshape(3,3,3)
arr

array([[[ 3,  6,  9],
        [12, 15, 18],
        [21, 24, 27]],

       [[30, 33, 36],
        [39, 42, 45],
        [48, 51, 54]],

       [[57, 60, 63],
        [66, 69, 72],
        [75, 78, 81]]])

In [62]:
# Finding the value of last limit by using fuctions
# x = 3
# s = 3
# n = 27
# y = (n*s)+x
# y