# Practice for Numpy Advance
## 1. Arthimetic with Numpy Arrays

In [2]:
import numpy as np
arr = np.arange(1,10, step = 2)
arr

array([1, 3, 5, 7, 9])

In [3]:
# Performing arthimetic operations on 1D Array

arr = arr + arr 
arr

array([ 2,  6, 10, 14, 18])

In [4]:
arr = arr - arr 
arr

array([0, 0, 0, 0, 0])

In [5]:
arr = np.arange(1,10, step = 2)
arr = arr * arr
arr

array([ 1,  9, 25, 49, 81])

In [6]:
arr = arr/3
arr

array([ 0.33333333,  3.        ,  8.33333333, 16.33333333, 27.        ])

In [7]:
arr = np.arange(1,10, step = 2)
arr = arr**arr
arr

array([        1,        27,      3125,    823543, 387420489])

In [8]:
# Perfroming Arthimetic Operations on 2D Array

arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
arr = arr + arr
arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [10]:
arr = arr - arr
arr

array([[0, 0, 0],
       [0, 0, 0]])

In [11]:
arr = np.array([[1,2,3],[4,5,6]])
arr = arr * arr
arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [12]:
arr = np.array([[1,2,3],[4,5,6]])
arr = arr/arr
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
arr = np.array([[1,2,3],[4,5,6]])
arr = arr**2
arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [14]:
# Same arthimetic operations can be done on a 3D Array

arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [16]:
arr.shape

(2, 2, 3)

In [17]:
arr = arr + arr
arr

array([[[ 2,  4,  6],
        [ 8, 10, 12]],

       [[14, 16, 18],
        [20, 22, 24]]])

# Basic Indexing & Slicing

In [20]:
arr = np.arange(2,30, step=2)
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

### Indexing & Slicing a 1D Array

In [21]:
# If we want to get a value at index 4 we use this command

arr[4]

10

In [22]:
# It is just like indexing a list 

arr[:5]

array([ 2,  4,  6,  8, 10])

In [24]:
# For slicing

arr_slice = arr[5:8]
arr_slice

array([12, 14, 16])

In [28]:
arr[2:6] = 4
arr_slice = arr[2:6]
arr_slice

array([4, 4, 4, 4])

In [29]:
arr

array([ 2,  4,  4,  4,  4,  4, 14, 16, 18, 20, 22, 24, 26, 28])

In [30]:
arr_slice[:] = 12345
arr

array([    2,     4, 12345, 12345, 12345, 12345,    14,    16,    18,
          20,    22,    24,    26,    28])

### Indexing a 2D Array

In [31]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
# We can index a 2D array by giving 2 things which is number of row & number of column

arr[0][1]

2

In [34]:
# The above command can also be written as

arr[0,1]

2

### Indexing a 3D Array

In [35]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [36]:
arr.shape

(2, 2, 3)

In [37]:
# Indexing of a 3D array is done by giving 3 parameters
# first parameter : Index of a 2D array
# second parameter : Row number of a 2D array
# third parameter : Cloumn number of a 2D array
# Like in a 3D tensor for obtaining the value of "8" we have to give the command like :

arr[1,0,1]


8

### Slicing a 2D Array

In [38]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
arr[:2,1:]

array([[2, 3],
       [5, 6]])

In [41]:
# The above command took first two rows of matrix and the it take last two columns of matrix

# Boolean Indexing

In [43]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
names


array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [44]:
data = np.random.randn(7,4)
data

array([[ 0.60476517,  0.62374748,  0.00668191,  0.72785248],
       [-0.32291712, -0.35358629,  1.23325678, -1.69223618],
       [ 0.93853002,  0.33994848, -0.41637696, -0.67859963],
       [ 1.00563325, -1.9754178 , -1.84716381, -1.17853706],
       [ 1.16454641,  0.24530778,  1.44788669, -0.50033756],
       [-0.21600112,  0.36535064,  1.03976943, -0.70135659],
       [-2.30985427, -0.84636093, -0.74719562,  0.13898542]])

In [46]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [47]:
data[names == "Bob"]

array([[ 0.60476517,  0.62374748,  0.00668191,  0.72785248],
       [ 1.00563325, -1.9754178 , -1.84716381, -1.17853706]])

# Transposing Arrays & Swapping Axes

In [48]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [49]:
# Now we can change the matrix formation by applying transpose 
# It just turns no. of rows in to column & no. of column into rows i.e it converts a (3 x 5) matrix into (5 x 3) matrix

arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [51]:
# Checking transpose function on a 3D array

arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [52]:
arr.T

array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]])

In [53]:
# It converts (2,2,3) tensor into (3,2,2) tensor

| Function | Description|
|----------|------------|
|abs, fabs| Absolute Value |
|sqrt| Square root |
|square| Square of element|
|exp | Exponent of element|
|log | Natural Logarithm|
|sign| Sign of each element|
|ceil | Ceil of each element|
|floor | floor of each element|
|rint | round element to the nearest integer|
|modf | return fraction and integral parts of array as a separate array|